### ISSUE TITLE
Add back bools

### ISSUE THREAD

**Issue by CraigRhodes** [PLT-DCL/dcl#4]

**Comment by wessilfie** [comment]
let's do this today or tomorrow; shouldn't take too long either. @ashutoshnanda should we do this based on your make-doubles-work branch or build it into string-work/master?

**Comment by CraigRhodes** [comment]
Look at these changes to add them back:
https://github.com/PLT-DCL/dcl/commit/f337db26ae07398cfa21180e903455f98df32b9c
